language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - sh ./tests/install_dependencies.sh
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - phpenv rehash

script:
  - mkdir -p build/cov
  - php vendor/bin/phpunit -c phpunit.xml.dist 

after_script:
  - php vendor/bin/coveralls -v
